# Generated by Django 4.1 on 2022-09-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_book_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_deatails',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='book_deatails',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book_deatails',
            name='book_img',
            field=models.ImageField(blank=True, default='bookimg/default.jpg', max_length=200, null=True, upload_to='bookimg/'),
        ),
    ]
