# Generated by Django 4.1 on 2022-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_book_deatails_city_book_deatails_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_deatails',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
