# Generated by Django 4.1 on 2022-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_book_deatails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_deatails',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
