# Generated by Django 4.1 on 2023-02-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_storemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemsg',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.book_deatails'),
        ),
    ]
