# Generated by Django 4.1 on 2023-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_send_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_message',
            name='book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
