# Generated by Django 4.1 on 2023-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_send_message_cuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_message',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=50),
        ),
    ]
