# Generated by Django 4.1 on 2023-02-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_donate_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_message',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.book_deatails'),
        ),
    ]
