# Generated by Django 4.1 on 2023-03-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_send_message_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_deatails',
            old_name='user',
            new_name='bookowner',
        ),
    ]
