# Generated by Django 4.1 on 2023-03-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_user_book_deatails_bookowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_deatails',
            old_name='bookowner',
            new_name='user',
        ),
    ]
