# Generated by Django 4.1 on 2023-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_bookowner_book_deatails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate_book',
            old_name='book_auth',
            new_name='qtybook',
        ),
        migrations.RemoveField(
            model_name='donate_book',
            name='book_img',
        ),
        migrations.RemoveField(
            model_name='donate_book',
            name='city',
        ),
        migrations.AddField(
            model_name='donate_book',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donate_book',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donate_book',
            name='pickdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
